name: update-docs

on: workflow_dispatch

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@2270f39ef63c3edf50be34da68c039eca5e15c15
        with:
          version: 6.31.0
      - uses: actions/setup-node@v2
        with:
          cache: pnpm
          node-version-file: .nvmrc
          registry-url: https://npm.pkg.github.com
      - run: pnpm install --ignore-scripts --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm build
      - run: pnpm docgen
      - uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: phyla.ziorobo.co
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
